# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-24 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effluent_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npdes_id', models.CharField(default='NA', max_length=9)),
                ('version_nmbr', models.IntegerField(null=True)),
                ('activity_id', models.IntegerField(default=0)),
                ('npdes_violation_id', models.IntegerField(default=0)),
                ('perm_feature_nmbr', models.CharField(default='NA', max_length=4)),
                ('permit_activity_id', models.IntegerField(default=0)),
                ('dmr_form_value_id', models.IntegerField(default=0)),
                ('dmr_value_nmbr', models.FloatField(default=0)),
                ('dmr_value_id', models.IntegerField(default=0, null=True)),
                ('dmr_parameter_id', models.IntegerField(default=0, null=True)),
                ('nodi_code', models.CharField(blank=True, max_length=3)),
                ('adjusted_dmr_value_nmbr', models.DecimalField(decimal_places=5, max_digits=22, null=True)),
                ('violation_type_code', models.CharField(blank=True, max_length=6)),
                ('violation_type_desc', models.CharField(blank=True, max_length=100)),
                ('violation_code', models.CharField(default='NA', max_length=5)),
                ('violation_desc', models.CharField(default='NA', max_length=100)),
                ('parameter_code', models.CharField(default='NA', max_length=5)),
                ('parameter_desc', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwp_name', models.CharField(max_length=150)),
                ('fac_lat', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('fac_long', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('d_qhome', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Permittees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_num', models.CharField(default='00', max_length=2)),
                ('source_id', models.CharField(max_length=30)),
                ('registry_id', models.CharField(max_length=36)),
                ('cwp_name', models.CharField(max_length=80)),
                ('cwp_street', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('cwp_city', models.CharField(default='DEFAULT VALUE', max_length=60)),
                ('cwp_state', models.CharField(default='NA', max_length=2)),
                ('cwp_facility_type_indicator', models.CharField(default='', max_length=10)),
                ('cwp_major_minor', models.CharField(default='0', max_length=1)),
                ('cwp_qtrs_in_nc', models.CharField(default='N/A', max_length=5)),
                ('cwp_current_viol', models.CharField(default='N/A', max_length=5)),
                ('fac_lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('fac_long', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('cwp_e90', models.CharField(default='N/A', max_length=22)),
                ('cwp_formal_ea', models.CharField(default='N/A', max_length=5)),
                ('cwp_days_last_inspection', models.CharField(default='N/A', max_length=5)),
                ('poll_in_violation', models.CharField(default='NONE', max_length=300)),
            ],
        ),
    ]
