# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effluent_data',
            name='adjusted_dmr_standard_units',
            field=models.DecimalField(decimal_places=5, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='days_late',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='dmr_value_standard_units',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='exceedance_pct',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='limit_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='monitoring_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='rnc_detection_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='rnc_detection_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='rnc_detection_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='rnc_resolution_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='rnc_resolution_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='rnc_resolution_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='statistical_base_code',
            field=models.CharField(default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='statistical_base_monthly_avg',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='unit_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='value_qualifier_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='value_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effluent_data',
            name='value_type_code',
            field=models.CharField(default='NA', max_length=3),
        ),
    ]
