# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-24 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_auto_20170524_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effluent_data',
            name='rnc_detection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='effluent_data',
            name='rnc_resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
